In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


In [5]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6]) 

[2 3 4 5 6]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) 


[5 6 7]


In [11]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

[2 4]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2]) 

[1 3 5 7]


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]
